"""Full NeetCode 150 (incl. Blind 75) problem catalog for the in-app IDE.

Each entry: title, difficulty, topic (pattern), one-line statement, a Python
starter signature, the LeetCode URL, and whether it is part of Blind 75.
Generated/curated data — solved in-app and reviewed by the AI tutor."""
from __future__ import annotations

CATALOG = {
    'two-sum': {
        'title': 'Two Sum',
        'difficulty': 'Easy', 'topic': 'Arrays & Hashing',
        'statement': 'Given an array of integers nums and an integer target, return the indices of the two numbers that add up to target. Exactly one solution exists and you may not use the same element twice.',
        'func': 'twoSum',
        'starter': 'def twoSum(nums, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/two-sum/',
        'blind75': True,
    },
    'contains-duplicate': {
        'title': 'Contains Duplicate',
        'difficulty': 'Easy', 'topic': 'Arrays & Hashing',
        'statement': 'Given an integer array nums, return true if any value appears at least twice in the array, and false if every element is distinct.',
        'func': 'containsDuplicate',
        'starter': 'def containsDuplicate(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/contains-duplicate/',
        'blind75': True,
    },
    'valid-anagram': {
        'title': 'Valid Anagram',
        'difficulty': 'Easy', 'topic': 'Arrays & Hashing',
        'statement': 'Given two strings s and t, return true if t is an anagram of s (a rearrangement using exactly the same characters with the same counts), otherwise return false.',
        'func': 'isAnagram',
        'starter': 'def isAnagram(s, t):\n    pass\n',
        'url': 'https://leetcode.com/problems/valid-anagram/',
        'blind75': True,
    },
    'group-anagrams': {
        'title': 'Group Anagrams',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': 'Given an array of strings strs, group the anagrams together and return the groups as a list of lists in any order. Two strings are anagrams if one can be rearranged to form the other.',
        'func': 'groupAnagrams',
        'starter': 'def groupAnagrams(strs):\n    pass\n',
        'url': 'https://leetcode.com/problems/group-anagrams/',
        'blind75': True,
    },
    'top-k-frequent-elements': {
        'title': 'Top K Frequent Elements',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': 'Given an integer array nums and an integer k, return the k most frequent elements. The answer may be returned in any order.',
        'func': 'topKFrequent',
        'starter': 'def topKFrequent(nums, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/top-k-frequent-elements/',
        'blind75': True,
    },
    'product-of-array-except-self': {
        'title': 'Product Of Array Except Self',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': 'Given an integer array nums, return an array answer where answer[i] is the product of all elements of nums except nums[i]. Solve it without using division and in O(n) time.',
        'func': 'productExceptSelf',
        'starter': 'def productExceptSelf(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/product-of-array-except-self/',
        'blind75': True,
    },
    'encode-and-decode-strings': {
        'title': 'Encode And Decode Strings',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': 'Design an algorithm to encode a list of strings into a single string that can be sent over a network, and decode that single string back into the original list of strings. Implement encode and decode methods that round-trip any list of strings.',
        'func': 'encode',
        'starter': 'def encode(strs):\n    pass\n\ndef decode(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/encode-and-decode-strings/',
        'blind75': True,
    },
    'longest-consecutive-sequence': {
        'title': 'Longest Consecutive Sequence',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': 'Given an unsorted array of integers nums, return the length of the longest sequence of consecutive integers (elements differing by one). The algorithm must run in O(n) time.',
        'func': 'longestConsecutive',
        'starter': 'def longestConsecutive(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/longest-consecutive-sequence/',
        'blind75': True,
    },
    'valid-palindrome': {
        'title': 'Valid Palindrome',
        'difficulty': 'Easy', 'topic': 'Two Pointers',
        'statement': 'Given a string s, return true if it is a palindrome when considering only alphanumeric characters and ignoring case, otherwise return false.',
        'func': 'isPalindrome',
        'starter': 'def isPalindrome(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/valid-palindrome/',
        'blind75': True,
    },
    '3sum': {
        'title': '3Sum',
        'difficulty': 'Medium', 'topic': 'Two Pointers',
        'statement': 'Given an integer array nums, return all unique triplets [nums[i], nums[j], nums[k]] with distinct indices such that they sum to zero. The solution set must not contain duplicate triplets.',
        'func': 'threeSum',
        'starter': 'def threeSum(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/3sum/',
        'blind75': True,
    },
    'container-with-most-water': {
        'title': 'Container With Most Water',
        'difficulty': 'Medium', 'topic': 'Two Pointers',
        'statement': 'Given an integer array height where each element is the height of a vertical line at that index, find two lines that together with the x-axis form a container holding the most water, and return that maximum area.',
        'func': 'maxArea',
        'starter': 'def maxArea(height):\n    pass\n',
        'url': 'https://leetcode.com/problems/container-with-most-water/',
        'blind75': True,
    },
    'best-time-to-buy-and-sell-stock': {
        'title': 'Best Time To Buy And Sell Stock',
        'difficulty': 'Easy', 'topic': 'Sliding Window',
        'statement': 'Given an array prices where prices[i] is the price of a stock on day i, return the maximum profit achievable by buying on one day and selling on a later day. Return 0 if no profit is possible.',
        'func': 'maxProfit',
        'starter': 'def maxProfit(prices):\n    pass\n',
        'url': 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
        'blind75': True,
    },
    'longest-substring-without-repeating-characters': {
        'title': 'Longest Substring Without Repeating Characters',
        'difficulty': 'Medium', 'topic': 'Sliding Window',
        'statement': 'Given a string s, return the length of the longest substring that contains no repeating characters.',
        'func': 'lengthOfLongestSubstring',
        'starter': 'def lengthOfLongestSubstring(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        'blind75': True,
    },
    'longest-repeating-character-replacement': {
        'title': 'Longest Repeating Character Replacement',
        'difficulty': 'Medium', 'topic': 'Sliding Window',
        'statement': 'Given a string s and an integer k, you may replace at most k characters with any uppercase English letter. Return the length of the longest substring containing the same letter you can obtain after performing the replacements.',
        'func': 'characterReplacement',
        'starter': 'def characterReplacement(s, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/longest-repeating-character-replacement/',
        'blind75': True,
    },
    'minimum-window-substring': {
        'title': 'Minimum Window Substring',
        'difficulty': 'Hard', 'topic': 'Sliding Window',
        'statement': 'Given strings s and t, return the smallest substring of s that contains every character of t including duplicates. If no such substring exists, return the empty string; the answer is guaranteed unique.',
        'func': 'minWindow',
        'starter': 'def minWindow(s, t):\n    pass\n',
        'url': 'https://leetcode.com/problems/minimum-window-substring/',
        'blind75': True,
    },
    'valid-parentheses': {
        'title': 'Valid Parentheses',
        'difficulty': 'Easy', 'topic': 'Stack',
        'statement': "Given a string s containing only the characters '()[]{}', return true if every open bracket is closed by the matching type in the correct order, otherwise return false.",
        'func': 'isValid',
        'starter': 'def isValid(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/valid-parentheses/',
        'blind75': True,
    },
    'find-minimum-in-rotated-sorted-array': {
        'title': 'Find Minimum In Rotated Sorted Array',
        'difficulty': 'Medium', 'topic': 'Binary Search',
        'statement': 'Given a sorted array of unique integers nums that has been rotated an unknown number of times, return the minimum element. The algorithm must run in O(log n) time.',
        'func': 'findMin',
        'starter': 'def findMin(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
        'blind75': True,
    },
    'search-in-rotated-sorted-array': {
        'title': 'Search In Rotated Sorted Array',
        'difficulty': 'Medium', 'topic': 'Binary Search',
        'statement': 'Given a rotated sorted array of distinct integers nums and a target value, return the index of target if present, otherwise return -1. The algorithm must run in O(log n) time.',
        'func': 'search',
        'starter': 'def search(nums, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
        'blind75': True,
    },
    'reverse-linked-list': {
        'title': 'Reverse Linked List',
        'difficulty': 'Easy', 'topic': 'Linked List',
        'statement': 'Given the head of a singly linked list, reverse the list and return the head of the reversed list.',
        'func': 'reverseList',
        'starter': 'def reverseList(head):\n    pass\n',
        'url': 'https://leetcode.com/problems/reverse-linked-list/',
        'blind75': True,
    },
    'merge-two-sorted-lists': {
        'title': 'Merge Two Sorted Lists',
        'difficulty': 'Easy', 'topic': 'Linked List',
        'statement': 'Given the heads of two sorted singly linked lists list1 and list2, merge them into one sorted linked list by splicing the nodes together, and return the head of the merged list.',
        'func': 'mergeTwoLists',
        'starter': 'def mergeTwoLists(list1, list2):\n    pass\n',
        'url': 'https://leetcode.com/problems/merge-two-sorted-lists/',
        'blind75': True,
    },
    'reorder-list': {
        'title': 'Reorder List',
        'difficulty': 'Medium', 'topic': 'Linked List',
        'statement': 'Given the head of a singly linked list, reorder it from L0->L1->...->Ln-1->Ln into L0->Ln->L1->Ln-1->L2->Ln-2->... by reversing the second half and interleaving. Modify the nodes in place without returning anything.',
        'func': 'reorderList',
        'starter': 'def reorderList(head):\n    pass\n',
        'url': 'https://leetcode.com/problems/reorder-list/',
        'blind75': True,
    },
    'remove-nth-node-from-end-of-list': {
        'title': 'Remove Nth Node From End Of List',
        'difficulty': 'Medium', 'topic': 'Linked List',
        'statement': 'Given the head of a linked list, remove the nth node counting from the end of the list and return the head of the modified list.',
        'func': 'removeNthFromEnd',
        'starter': 'def removeNthFromEnd(head, n):\n    pass\n',
        'url': 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
        'blind75': True,
    },
    'linked-list-cycle': {
        'title': 'Linked List Cycle',
        'difficulty': 'Easy', 'topic': 'Linked List',
        'statement': 'Given the head of a linked list, return true if the list contains a cycle (some node can be reached again by following next pointers), otherwise return false.',
        'func': 'hasCycle',
        'starter': 'def hasCycle(head):\n    pass\n',
        'url': 'https://leetcode.com/problems/linked-list-cycle/',
        'blind75': True,
    },
    'merge-k-sorted-lists': {
        'title': 'Merge K Sorted Lists',
        'difficulty': 'Hard', 'topic': 'Heap',
        'statement': 'Given an array lists of k linked-list heads, each sorted in ascending order, merge all the lists into one sorted linked list and return its head.',
        'func': 'mergeKLists',
        'starter': 'def mergeKLists(lists):\n    pass\n',
        'url': 'https://leetcode.com/problems/merge-k-sorted-lists/',
        'blind75': True,
    },
    'invert-binary-tree': {
        'title': 'Invert Binary Tree',
        'difficulty': 'Easy', 'topic': 'Trees',
        'statement': 'Given the root of a binary tree, invert the tree by swapping the left and right children of every node, and return the root.',
        'func': 'invertTree',
        'starter': 'def invertTree(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/invert-binary-tree/',
        'blind75': True,
    },
    'maximum-depth-of-binary-tree': {
        'title': 'Maximum Depth Of Binary Tree',
        'difficulty': 'Easy', 'topic': 'Trees',
        'statement': 'Given the root of a binary tree, return its maximum depth, the number of nodes along the longest path from the root down to the farthest leaf.',
        'func': 'maxDepth',
        'starter': 'def maxDepth(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        'blind75': True,
    },
    'same-tree': {
        'title': 'Same Tree',
        'difficulty': 'Easy', 'topic': 'Trees',
        'statement': 'Given the roots p and q of two binary trees, return true if the trees are structurally identical and all corresponding nodes have the same value, otherwise return false.',
        'func': 'isSameTree',
        'starter': 'def isSameTree(p, q):\n    pass\n',
        'url': 'https://leetcode.com/problems/same-tree/',
        'blind75': True,
    },
    'subtree-of-another-tree': {
        'title': 'Subtree Of Another Tree',
        'difficulty': 'Easy', 'topic': 'Trees',
        'statement': 'Given the roots of two binary trees root and subRoot, return true if there is a subtree of root that has the same structure and node values as subRoot, otherwise return false.',
        'func': 'isSubtree',
        'starter': 'def isSubtree(root, subRoot):\n    pass\n',
        'url': 'https://leetcode.com/problems/subtree-of-another-tree/',
        'blind75': True,
    },
    'lowest-common-ancestor-of-a-binary-search-tree': {
        'title': 'Lowest Common Ancestor Of A Binary Search Tree',
        'difficulty': 'Medium', 'topic': 'Trees',
        'statement': 'Given the root of a binary search tree and two nodes p and q present in it, return their lowest common ancestor, the deepest node that has both p and q as descendants (a node may be a descendant of itself).',
        'func': 'lowestCommonAncestor',
        'starter': 'def lowestCommonAncestor(root, p, q):\n    pass\n',
        'url': 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
        'blind75': True,
    },
    'binary-tree-level-order-traversal': {
        'title': 'Binary Tree Level Order Traversal',
        'difficulty': 'Medium', 'topic': 'Trees',
        'statement': 'Given the root of a binary tree, return the level-order traversal of its node values as a list of lists, where each inner list contains the values at one level from left to right.',
        'func': 'levelOrder',
        'starter': 'def levelOrder(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
        'blind75': True,
    },
    'validate-binary-search-tree': {
        'title': 'Validate Binary Search Tree',
        'difficulty': 'Medium', 'topic': 'Trees',
        'statement': "Given the root of a binary tree, return true if it is a valid binary search tree, meaning every node's left subtree contains only smaller values and its right subtree only larger values.",
        'func': 'isValidBST',
        'starter': 'def isValidBST(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/validate-binary-search-tree/',
        'blind75': True,
    },
    'kth-smallest-element-in-a-bst': {
        'title': 'Kth Smallest Element in a BST',
        'difficulty': 'Medium', 'topic': 'Trees',
        'statement': 'Given the root of a binary search tree and an integer k, return the kth smallest value (1-indexed) among all node values in the tree.',
        'func': 'kthSmallest',
        'starter': 'def kthSmallest(root, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
        'blind75': True,
    },
    'construct-binary-tree-from-preorder-and-inorder-traversal': {
        'title': 'Construct Binary Tree From Preorder And Inorder Traversal',
        'difficulty': 'Medium', 'topic': 'Trees',
        'statement': 'Given two integer arrays preorder and inorder representing the preorder and inorder traversals of a binary tree with unique values, construct and return the root of the binary tree.',
        'func': 'buildTree',
        'starter': 'def buildTree(preorder, inorder):\n    pass\n',
        'url': 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
        'blind75': True,
    },
    'binary-tree-maximum-path-sum': {
        'title': 'Binary Tree Maximum Path Sum',
        'difficulty': 'Hard', 'topic': 'Trees',
        'statement': 'Given the root of a binary tree, return the maximum path sum of any non-empty path, where a path is a sequence of connected nodes (not required to pass through the root) and each node appears at most once.',
        'func': 'maxPathSum',
        'starter': 'def maxPathSum(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
        'blind75': True,
    },
    'serialize-and-deserialize-binary-tree': {
        'title': 'Serialize And Deserialize Binary Tree',
        'difficulty': 'Hard', 'topic': 'Trees',
        'statement': 'Design an algorithm to serialize a binary tree into a string and deserialize that string back into the identical tree structure. Implement serialize and deserialize so that the tree round-trips correctly.',
        'func': 'Codec',
        'starter': 'class Codec:\n    def serialize(self, root):\n        pass\n\n    def deserialize(self, data):\n        pass\n',
        'url': 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
        'blind75': True,
    },
    'implement-trie-prefix-tree': {
        'title': 'Implement Trie (Prefix Tree)',
        'difficulty': 'Medium', 'topic': 'Tries',
        'statement': 'Design a trie (prefix tree) supporting insert(word), search(word) which returns true only for previously inserted exact words, and startsWith(prefix) which returns true if any inserted word begins with the given prefix.',
        'func': 'Trie',
        'starter': 'class Trie:\n    def __init__(self):\n        pass\n\n    def insert(self, word):\n        pass\n\n    def search(self, word):\n        pass\n\n    def startsWith(self, prefix):\n        pass\n',
        'url': 'https://leetcode.com/problems/implement-trie-prefix-tree/',
        'blind75': True,
    },
    'design-add-and-search-words-data-structure': {
        'title': 'Design Add And Search Words Data Structure',
        'difficulty': 'Medium', 'topic': 'Tries',
        'statement': "Design a data structure supporting addWord(word) and search(word), where search may contain the '.' wildcard that matches any single character. search returns true if any stored word matches the query.",
        'func': 'WordDictionary',
        'starter': 'class WordDictionary:\n    def __init__(self):\n        pass\n\n    def addWord(self, word):\n        pass\n\n    def search(self, word):\n        pass\n',
        'url': 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
        'blind75': True,
    },
    'word-search-ii': {
        'title': 'Word Search II',
        'difficulty': 'Hard', 'topic': 'Tries',
        'statement': 'Given an m x n grid of characters board and a list of strings words, return all words that can be formed by sequentially adjacent (horizontally or vertically) cells, where each cell is used at most once per word.',
        'func': 'findWords',
        'starter': 'def findWords(board, words):\n    pass\n',
        'url': 'https://leetcode.com/problems/word-search-ii/',
        'blind75': True,
    },
    'find-median-from-data-stream': {
        'title': 'Find Median From Data Stream',
        'difficulty': 'Hard', 'topic': 'Heap',
        'statement': 'Design a data structure that supports adding integers from a data stream and finding the median of all elements seen so far. Implement addNum(num) to insert a value and findMedian() to return the median (the average of the two middle values if the count is even).',
        'func': 'MedianFinder',
        'starter': 'class MedianFinder:\n    def __init__(self):\n        pass\n\n    def addNum(self, num):\n        pass\n\n    def findMedian(self):\n        pass\n',
        'url': 'https://leetcode.com/problems/find-median-from-data-stream/',
        'blind75': True,
    },
    'combination-sum': {
        'title': 'Combination Sum',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given an array of distinct integers candidates and a target integer, return all unique combinations of candidates that sum to target. The same number may be chosen an unlimited number of times, and two combinations are unique if the chosen frequency of at least one number differs.',
        'func': 'combinationSum',
        'starter': 'def combinationSum(candidates, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/combination-sum/',
        'blind75': True,
    },
    'word-search': {
        'title': 'Word Search',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given an m x n grid of characters board and a string word, return True if word exists in the grid. The word can be constructed from sequentially adjacent cells (horizontally or vertically), where the same cell may not be used more than once.',
        'func': 'exist',
        'starter': 'def exist(board, word):\n    pass\n',
        'url': 'https://leetcode.com/problems/word-search/',
        'blind75': True,
    },
    'number-of-islands': {
        'title': 'Number Of Islands',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': "Given an m x n binary grid of '1's (land) and '0's (water), return the number of islands. An island is a group of horizontally or vertically adjacent land cells, and all four edges of the grid are surrounded by water.",
        'func': 'numIslands',
        'starter': 'def numIslands(grid):\n    pass\n',
        'url': 'https://leetcode.com/problems/number-of-islands/',
        'blind75': True,
    },
    'clone-graph': {
        'title': 'Clone Graph',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given a reference to a node in a connected undirected graph where each node holds a value and a list of neighbors, return a deep copy (clone) of the entire graph.',
        'func': 'cloneGraph',
        'starter': 'def cloneGraph(node):\n    pass\n',
        'url': 'https://leetcode.com/problems/clone-graph/',
        'blind75': True,
    },
    'pacific-atlantic-water-flow': {
        'title': 'Pacific Atlantic Water Flow',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given an m x n matrix heights of cell heights, where the Pacific Ocean touches the top and left edges and the Atlantic Ocean touches the bottom and right edges, water can flow from a cell to an adjacent cell of equal or lower height. Return a list of coordinates [r, c] from which water can flow to both oceans.',
        'func': 'pacificAtlantic',
        'starter': 'def pacificAtlantic(heights):\n    pass\n',
        'url': 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
        'blind75': True,
    },
    'course-schedule': {
        'title': 'Course Schedule',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given numCourses labeled 0 to numCourses-1 and a list prerequisites where [a, b] means you must take course b before course a, return True if you can finish all courses. This is equivalent to detecting whether the directed graph has no cycle.',
        'func': 'canFinish',
        'starter': 'def canFinish(numCourses, prerequisites):\n    pass\n',
        'url': 'https://leetcode.com/problems/course-schedule/',
        'blind75': True,
    },
    'graph-valid-tree': {
        'title': 'Graph Valid Tree',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given n nodes labeled 0 to n-1 and a list of undirected edges, return True if these edges form a valid tree. A valid tree is fully connected and contains no cycles (exactly n-1 edges with all nodes reachable).',
        'func': 'validTree',
        'starter': 'def validTree(n, edges):\n    pass\n',
        'url': 'https://leetcode.com/problems/graph-valid-tree/',
        'blind75': True,
    },
    'number-of-connected-components-in-an-undirected-graph': {
        'title': 'Number Of Connected Components In An Undirected Graph',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given n nodes labeled 0 to n-1 and a list of undirected edges, return the number of connected components in the graph.',
        'func': 'countComponents',
        'starter': 'def countComponents(n, edges):\n    pass\n',
        'url': 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
        'blind75': True,
    },
    'alien-dictionary': {
        'title': 'Alien Dictionary',
        'difficulty': 'Hard', 'topic': 'Graphs',
        'statement': 'Given a list of words sorted lexicographically according to the rules of an unknown alien language, derive and return a string of the unique letters in the correct alien order. Return an empty string if no valid ordering exists; if multiple valid orders exist, return any.',
        'func': 'alienOrder',
        'starter': 'def alienOrder(words):\n    pass\n',
        'url': 'https://leetcode.com/problems/alien-dictionary/',
        'blind75': True,
    },
    'climbing-stairs': {
        'title': 'Climbing Stairs',
        'difficulty': 'Easy', 'topic': '1-D DP',
        'statement': 'You are climbing a staircase that takes n steps to reach the top, and each time you can climb either 1 or 2 steps. Return the number of distinct ways to climb to the top.',
        'func': 'climbStairs',
        'starter': 'def climbStairs(n):\n    pass\n',
        'url': 'https://leetcode.com/problems/climbing-stairs/',
        'blind75': True,
    },
    'house-robber': {
        'title': 'House Robber',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an integer array nums representing the amount of money in each house arranged in a line, return the maximum amount you can rob without robbing two adjacent houses.',
        'func': 'rob',
        'starter': 'def rob(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/house-robber/',
        'blind75': True,
    },
    'house-robber-ii': {
        'title': 'House Robber II',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an integer array nums representing money in houses arranged in a circle (the first and last houses are adjacent), return the maximum amount you can rob without robbing two adjacent houses.',
        'func': 'rob',
        'starter': 'def rob(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/house-robber-ii/',
        'blind75': True,
    },
    'longest-palindromic-substring': {
        'title': 'Longest Palindromic Substring',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given a string s, return the longest contiguous substring of s that is a palindrome.',
        'func': 'longestPalindrome',
        'starter': 'def longestPalindrome(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/longest-palindromic-substring/',
        'blind75': True,
    },
    'palindromic-substrings': {
        'title': 'Palindromic Substrings',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given a string s, return the number of palindromic substrings in it. Substrings at different start or end positions are counted separately even if they consist of the same characters.',
        'func': 'countSubstrings',
        'starter': 'def countSubstrings(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/palindromic-substrings/',
        'blind75': True,
    },
    'decode-ways': {
        'title': 'Decode Ways',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': "A message of digits is encoded where 'A' maps to '1' through 'Z' to '26'. Given a string s containing only digits, return the number of ways to decode it, accounting for groupings of one or two digits that form valid letters (leading zeros are invalid).",
        'func': 'numDecodings',
        'starter': 'def numDecodings(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/decode-ways/',
        'blind75': True,
    },
    'coin-change': {
        'title': 'Coin Change',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an array coins of coin denominations and an integer amount, return the fewest number of coins needed to make up that amount. You may use each coin type an unlimited number of times; return -1 if the amount cannot be made.',
        'func': 'coinChange',
        'starter': 'def coinChange(coins, amount):\n    pass\n',
        'url': 'https://leetcode.com/problems/coin-change/',
        'blind75': True,
    },
    'maximum-product-subarray': {
        'title': 'Maximum Product Subarray',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an integer array nums, find a contiguous non-empty subarray that has the largest product, and return that product.',
        'func': 'maxProduct',
        'starter': 'def maxProduct(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/maximum-product-subarray/',
        'blind75': True,
    },
    'word-break': {
        'title': 'Word Break',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given a string s and a dictionary of strings wordDict, return True if s can be segmented into a space-separated sequence of one or more dictionary words. Words may be reused.',
        'func': 'wordBreak',
        'starter': 'def wordBreak(s, wordDict):\n    pass\n',
        'url': 'https://leetcode.com/problems/word-break/',
        'blind75': True,
    },
    'longest-increasing-subsequence': {
        'title': 'Longest Increasing Subsequence',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an integer array nums, return the length of the longest strictly increasing subsequence. A subsequence keeps the original order but need not be contiguous.',
        'func': 'lengthOfLIS',
        'starter': 'def lengthOfLIS(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/longest-increasing-subsequence/',
        'blind75': True,
    },
    'unique-paths': {
        'title': 'Unique Paths',
        'difficulty': 'Medium', 'topic': '2-D DP',
        'statement': 'A robot starts at the top-left corner of an m x n grid and can only move right or down. Return the number of distinct paths to reach the bottom-right corner.',
        'func': 'uniquePaths',
        'starter': 'def uniquePaths(m, n):\n    pass\n',
        'url': 'https://leetcode.com/problems/unique-paths/',
        'blind75': True,
    },
    'longest-common-subsequence': {
        'title': 'Longest Common Subsequence',
        'difficulty': 'Medium', 'topic': '2-D DP',
        'statement': 'Given two strings text1 and text2, return the length of their longest common subsequence. A subsequence keeps relative order but need not be contiguous; return 0 if there is none.',
        'func': 'longestCommonSubsequence',
        'starter': 'def longestCommonSubsequence(text1, text2):\n    pass\n',
        'url': 'https://leetcode.com/problems/longest-common-subsequence/',
        'blind75': True,
    },
    'maximum-subarray': {
        'title': 'Maximum Subarray',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an integer array nums, find the contiguous non-empty subarray with the largest sum and return that sum.',
        'func': 'maxSubArray',
        'starter': 'def maxSubArray(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/maximum-subarray/',
        'blind75': True,
    },
    'jump-game': {
        'title': 'Jump Game',
        'difficulty': 'Medium', 'topic': 'Greedy',
        'statement': 'Given an integer array nums where each element represents the maximum jump length from that position, return True if you can reach the last index starting from the first index.',
        'func': 'canJump',
        'starter': 'def canJump(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/jump-game/',
        'blind75': True,
    },
    'insert-interval': {
        'title': 'Insert Interval',
        'difficulty': 'Medium', 'topic': 'Intervals',
        'statement': 'Given a list of non-overlapping intervals sorted by start time and a new interval newInterval, insert it into the list so the result remains sorted and non-overlapping, merging where necessary, and return the updated list.',
        'func': 'insert',
        'starter': 'def insert(intervals, newInterval):\n    pass\n',
        'url': 'https://leetcode.com/problems/insert-interval/',
        'blind75': True,
    },
    'merge-intervals': {
        'title': 'Merge Intervals',
        'difficulty': 'Medium', 'topic': 'Intervals',
        'statement': 'Given an array of intervals where intervals[i] = [start, end], merge all overlapping intervals and return an array of the non-overlapping intervals that cover all the input intervals.',
        'func': 'merge',
        'starter': 'def merge(intervals):\n    pass\n',
        'url': 'https://leetcode.com/problems/merge-intervals/',
        'blind75': True,
    },
    'non-overlapping-intervals': {
        'title': 'Non Overlapping Intervals',
        'difficulty': 'Medium', 'topic': 'Intervals',
        'statement': 'Given an array of intervals, return the minimum number of intervals you must remove so that the remaining intervals are non-overlapping (intervals touching only at endpoints are not considered overlapping).',
        'func': 'eraseOverlapIntervals',
        'starter': 'def eraseOverlapIntervals(intervals):\n    pass\n',
        'url': 'https://leetcode.com/problems/non-overlapping-intervals/',
        'blind75': True,
    },
    'meeting-rooms': {
        'title': 'Meeting Rooms',
        'difficulty': 'Easy', 'topic': 'Intervals',
        'statement': 'Given an array of meeting time intervals where intervals[i] = [start, end], return True if a person could attend all meetings, i.e. no two meetings overlap.',
        'func': 'canAttendMeetings',
        'starter': 'def canAttendMeetings(intervals):\n    pass\n',
        'url': 'https://leetcode.com/problems/meeting-rooms/',
        'blind75': True,
    },
    'meeting-rooms-ii': {
        'title': 'Meeting Rooms II',
        'difficulty': 'Medium', 'topic': 'Intervals',
        'statement': 'Given an array of meeting time intervals where intervals[i] = [start, end], return the minimum number of conference rooms required to hold all meetings.',
        'func': 'minMeetingRooms',
        'starter': 'def minMeetingRooms(intervals):\n    pass\n',
        'url': 'https://leetcode.com/problems/meeting-rooms-ii/',
        'blind75': True,
    },
    'rotate-image': {
        'title': 'Rotate Image',
        'difficulty': 'Medium', 'topic': 'Math & Bit',
        'statement': 'Given an n x n 2D matrix representing an image, rotate it 90 degrees clockwise in place, modifying the input matrix directly without allocating another 2D matrix.',
        'func': 'rotate',
        'starter': 'def rotate(matrix):\n    pass\n',
        'url': 'https://leetcode.com/problems/rotate-image/',
        'blind75': True,
    },
    'spiral-matrix': {
        'title': 'Spiral Matrix',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': 'Given an m x n matrix, return all its elements in spiral order, starting from the top-left and traversing clockwise.',
        'func': 'spiralOrder',
        'starter': 'def spiralOrder(matrix):\n    pass\n',
        'url': 'https://leetcode.com/problems/spiral-matrix/',
        'blind75': True,
    },
    'set-matrix-zeroes': {
        'title': 'Set Matrix Zeroes',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': 'Given an m x n integer matrix, if an element is 0, set its entire row and column to 0. Do it in place.',
        'func': 'setZeroes',
        'starter': 'def setZeroes(matrix):\n    pass\n',
        'url': 'https://leetcode.com/problems/set-matrix-zeroes/',
        'blind75': True,
    },
    'number-of-1-bits': {
        'title': 'Number of 1 Bits',
        'difficulty': 'Easy', 'topic': 'Math & Bit',
        'statement': "Given an unsigned integer n, return the number of '1' bits in its binary representation (also known as the Hamming weight).",
        'func': 'hammingWeight',
        'starter': 'def hammingWeight(n):\n    pass\n',
        'url': 'https://leetcode.com/problems/number-of-1-bits/',
        'blind75': True,
    },
    'counting-bits': {
        'title': 'Counting Bits',
        'difficulty': 'Easy', 'topic': 'Math & Bit',
        'statement': 'Given an integer n, return an array ans of length n+1 where ans[i] is the number of 1 bits in the binary representation of i, for each i from 0 to n.',
        'func': 'countBits',
        'starter': 'def countBits(n):\n    pass\n',
        'url': 'https://leetcode.com/problems/counting-bits/',
        'blind75': True,
    },
    'reverse-bits': {
        'title': 'Reverse Bits',
        'difficulty': 'Easy', 'topic': 'Math & Bit',
        'statement': 'Given a 32-bit unsigned integer n, reverse the order of its bits and return the resulting integer.',
        'func': 'reverseBits',
        'starter': 'def reverseBits(n):\n    pass\n',
        'url': 'https://leetcode.com/problems/reverse-bits/',
        'blind75': True,
    },
    'missing-number': {
        'title': 'Missing Number',
        'difficulty': 'Easy', 'topic': 'Math & Bit',
        'statement': 'Given an array nums containing n distinct numbers taken from the range 0 to n, return the single number in that range that is missing from the array.',
        'func': 'missingNumber',
        'starter': 'def missingNumber(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/missing-number/',
        'blind75': True,
    },
    'sum-of-two-integers': {
        'title': 'Sum Of Two Integers',
        'difficulty': 'Medium', 'topic': 'Math & Bit',
        'statement': 'Given two integers a and b, return their sum without using the operators + and -, using bitwise operations instead.',
        'func': 'getSum',
        'starter': 'def getSum(a, b):\n    pass\n',
        'url': 'https://leetcode.com/problems/sum-of-two-integers/',
        'blind75': True,
    },
    'valid-sudoku': {
        'title': 'Valid Sudoku',
        'difficulty': 'Medium', 'topic': 'Arrays & Hashing',
        'statement': "Given a 9x9 Sudoku board (partially filled, empty cells marked with '.'), determine if it is valid. Only validate the filled cells: each row, each column, and each of the nine 3x3 sub-boxes must contain the digits 1-9 without repetition. The board does not need to be solvable. Return True if valid, else False.",
        'func': 'isValidSudoku',
        'starter': 'def isValidSudoku(board):\n    pass\n',
        'url': 'https://leetcode.com/problems/valid-sudoku/',
        'blind75': False,
    },
    'two-sum-ii-input-array-is-sorted': {
        'title': 'Two Sum II Input Array Is Sorted',
        'difficulty': 'Medium', 'topic': 'Two Pointers',
        'statement': 'Given a 1-indexed array of integers numbers sorted in non-decreasing order, find two numbers that add up to a specific target. Return their indices (1-based) as [index1, index2] with index1 < index2. There is exactly one solution and you may not use the same element twice; use only constant extra space.',
        'func': 'twoSum',
        'starter': 'def twoSum(numbers, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
        'blind75': False,
    },
    'trapping-rain-water': {
        'title': 'Trapping Rain Water',
        'difficulty': 'Hard', 'topic': 'Two Pointers',
        'statement': 'Given an array height representing an elevation map where the width of each bar is 1, compute how much water can be trapped after raining. Return the total trapped water as an integer.',
        'func': 'trap',
        'starter': 'def trap(height):\n    pass\n',
        'url': 'https://leetcode.com/problems/trapping-rain-water/',
        'blind75': False,
    },
    'permutation-in-string': {
        'title': 'Permutation In String',
        'difficulty': 'Medium', 'topic': 'Sliding Window',
        'statement': 'Given two strings s1 and s2, return True if s2 contains a permutation of s1 as a contiguous substring, otherwise return False. In other words, check whether any substring of s2 is an anagram of s1.',
        'func': 'checkInclusion',
        'starter': 'def checkInclusion(s1, s2):\n    pass\n',
        'url': 'https://leetcode.com/problems/permutation-in-string/',
        'blind75': False,
    },
    'sliding-window-maximum': {
        'title': 'Sliding Window Maximum',
        'difficulty': 'Hard', 'topic': 'Sliding Window',
        'statement': 'Given an integer array nums and a window size k, the window slides from left to right one position at a time. Return a list of the maximum value in each window of size k.',
        'func': 'maxSlidingWindow',
        'starter': 'def maxSlidingWindow(nums, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/sliding-window-maximum/',
        'blind75': False,
    },
    'min-stack': {
        'title': 'Min Stack',
        'difficulty': 'Medium', 'topic': 'Stack',
        'statement': 'Design a stack that supports push, pop, top, and retrieving the minimum element, each in O(1) time. Implement push(val), pop(), top() which returns the top element, and getMin() which returns the minimum element in the stack.',
        'func': 'MinStack',
        'starter': 'class MinStack:\n    def __init__(self):\n        pass\n\n    def push(self, val):\n        pass\n\n    def pop(self):\n        pass\n\n    def top(self):\n        pass\n\n    def getMin(self):\n        pass\n',
        'url': 'https://leetcode.com/problems/min-stack/',
        'blind75': False,
    },
    'evaluate-reverse-polish-notation': {
        'title': 'Evaluate Reverse Polish Notation',
        'difficulty': 'Medium', 'topic': 'Stack',
        'statement': 'Given an array tokens representing an arithmetic expression in Reverse Polish Notation, evaluate it and return the integer result. Valid operators are +, -, *, and /; division truncates toward zero. Operands are integers and the expression is always valid.',
        'func': 'evalRPN',
        'starter': 'def evalRPN(tokens):\n    pass\n',
        'url': 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
        'blind75': False,
    },
    'generate-parentheses': {
        'title': 'Generate Parentheses',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given an integer n, generate all combinations of n pairs of well-formed (balanced) parentheses. Return the list of all valid strings in any order.',
        'func': 'generateParenthesis',
        'starter': 'def generateParenthesis(n):\n    pass\n',
        'url': 'https://leetcode.com/problems/generate-parentheses/',
        'blind75': False,
    },
    'daily-temperatures': {
        'title': 'Daily Temperatures',
        'difficulty': 'Medium', 'topic': 'Stack',
        'statement': 'Given an array temperatures of daily temperatures, return an array answer where answer[i] is the number of days you must wait after day i to get a warmer temperature. If no future day is warmer, set answer[i] to 0.',
        'func': 'dailyTemperatures',
        'starter': 'def dailyTemperatures(temperatures):\n    pass\n',
        'url': 'https://leetcode.com/problems/daily-temperatures/',
        'blind75': False,
    },
    'car-fleet': {
        'title': 'Car Fleet',
        'difficulty': 'Medium', 'topic': 'Stack',
        'statement': "Cars head to a destination at target miles. Given arrays position and speed for each car (constant speed, cars cannot pass but can catch up and form a fleet moving at the slowest car's speed), return the number of car fleets that will arrive at the destination.",
        'func': 'carFleet',
        'starter': 'def carFleet(target, position, speed):\n    pass\n',
        'url': 'https://leetcode.com/problems/car-fleet/',
        'blind75': False,
    },
    'largest-rectangle-in-histogram': {
        'title': 'Largest Rectangle In Histogram',
        'difficulty': 'Hard', 'topic': 'Stack',
        'statement': 'Given an array heights representing the heights of bars in a histogram where each bar has width 1, return the area of the largest rectangle that can be formed within the histogram.',
        'func': 'largestRectangleArea',
        'starter': 'def largestRectangleArea(heights):\n    pass\n',
        'url': 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
        'blind75': False,
    },
    'binary-search': {
        'title': 'Binary Search',
        'difficulty': 'Easy', 'topic': 'Binary Search',
        'statement': 'Given a sorted (ascending) array of distinct integers nums and a target value, return the index of target if it exists, otherwise return -1. The algorithm must run in O(log n) time.',
        'func': 'search',
        'starter': 'def search(nums, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/binary-search/',
        'blind75': False,
    },
    'search-a-2d-matrix': {
        'title': 'Search A 2D Matrix',
        'difficulty': 'Medium', 'topic': 'Binary Search',
        'statement': 'Given an m x n matrix where each row is sorted in ascending order and the first integer of each row is greater than the last integer of the previous row, determine whether a target value exists in the matrix. Return True or False in O(log(m*n)) time.',
        'func': 'searchMatrix',
        'starter': 'def searchMatrix(matrix, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/search-a-2d-matrix/',
        'blind75': False,
    },
    'koko-eating-bananas': {
        'title': 'Koko Eating Bananas',
        'difficulty': 'Medium', 'topic': 'Binary Search',
        'statement': 'Given piles of bananas and h hours, Koko eats at a constant speed k bananas per hour, finishing at most one pile per hour. Return the minimum integer speed k such that she can eat all the bananas within h hours.',
        'func': 'minEatingSpeed',
        'starter': 'def minEatingSpeed(piles, h):\n    pass\n',
        'url': 'https://leetcode.com/problems/koko-eating-bananas/',
        'blind75': False,
    },
    'time-based-key-value-store': {
        'title': 'Time Based Key Value Store',
        'difficulty': 'Medium', 'topic': 'Binary Search',
        'statement': 'Design a time-based key-value store. Implement set(key, value, timestamp) to store a value, and get(key, timestamp) which returns the value set for key at the largest stored timestamp that is less than or equal to the given timestamp, or an empty string if none exists.',
        'func': 'TimeMap',
        'starter': 'class TimeMap:\n    def __init__(self):\n        pass\n\n    def set(self, key, value, timestamp):\n        pass\n\n    def get(self, key, timestamp):\n        pass\n',
        'url': 'https://leetcode.com/problems/time-based-key-value-store/',
        'blind75': False,
    },
    'median-of-two-sorted-arrays': {
        'title': 'Median Of Two Sorted Arrays',
        'difficulty': 'Hard', 'topic': 'Binary Search',
        'statement': 'Given two sorted arrays nums1 and nums2 of sizes m and n, return the median of the combined sorted array. The overall run time complexity should be O(log(m+n)).',
        'func': 'findMedianSortedArrays',
        'starter': 'def findMedianSortedArrays(nums1, nums2):\n    pass\n',
        'url': 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
        'blind75': False,
    },
    'add-two-numbers': {
        'title': 'Add Two Numbers',
        'difficulty': 'Medium', 'topic': 'Linked List',
        'statement': 'Given two non-empty linked lists representing two non-negative integers stored in reverse order (each node holds one digit), add the two numbers and return the sum as a linked list, also in reverse order. The numbers have no leading zeros except the number 0 itself.',
        'func': 'addTwoNumbers',
        'starter': 'def addTwoNumbers(l1, l2):\n    pass\n',
        'url': 'https://leetcode.com/problems/add-two-numbers/',
        'blind75': False,
    },
    'copy-list-with-random-pointer': {
        'title': 'Copy List With Random Pointer',
        'difficulty': 'Medium', 'topic': 'Linked List',
        'statement': 'Given the head of a linked list where each node has a next pointer and a random pointer that can point to any node in the list or None, construct and return a deep copy of the list. The copied nodes must be entirely new nodes with next and random pointers mirroring the original structure.',
        'func': 'copyRandomList',
        'starter': 'def copyRandomList(head):\n    pass\n',
        'url': 'https://leetcode.com/problems/copy-list-with-random-pointer/',
        'blind75': False,
    },
    'find-the-duplicate-number': {
        'title': 'Find The Duplicate Number',
        'difficulty': 'Medium', 'topic': 'Linked List',
        'statement': 'Given an array nums of n+1 integers where each integer is in the range [1, n] inclusive, there is exactly one number that appears more than once. Return the duplicate number without modifying the array and using only constant extra space.',
        'func': 'findDuplicate',
        'starter': 'def findDuplicate(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/find-the-duplicate-number/',
        'blind75': False,
    },
    'lru-cache': {
        'title': 'LRU Cache',
        'difficulty': 'Medium', 'topic': 'Linked List',
        'statement': 'Design a Least Recently Used (LRU) cache with a given capacity. Implement get(key) which returns the value or -1 if not present, and put(key, value) which inserts or updates the value, evicting the least recently used key when capacity is exceeded. Both operations must run in O(1) average time.',
        'func': 'LRUCache',
        'starter': 'class LRUCache:\n    def __init__(self, capacity):\n        pass\n\n    def get(self, key):\n        pass\n\n    def put(self, key, value):\n        pass\n',
        'url': 'https://leetcode.com/problems/lru-cache/',
        'blind75': False,
    },
    'balanced-binary-tree': {
        'title': 'Balanced Binary Tree',
        'difficulty': 'Easy', 'topic': 'Trees',
        'statement': 'Given the root of a binary tree, determine whether it is height-balanced, meaning for every node the heights of its left and right subtrees differ by at most one. Return True if balanced, otherwise False.',
        'func': 'isBalanced',
        'starter': 'def isBalanced(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/balanced-binary-tree/',
        'blind75': False,
    },
    'diameter-of-binary-tree': {
        'title': 'Diameter Of Binary Tree',
        'difficulty': 'Easy', 'topic': 'Trees',
        'statement': 'Given the root of a binary tree, return the length of its diameter, the number of edges on the longest path between any two nodes in the tree. This path may or may not pass through the root.',
        'func': 'diameterOfBinaryTree',
        'starter': 'def diameterOfBinaryTree(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/diameter-of-binary-tree/',
        'blind75': False,
    },
    'count-good-nodes-in-binary-tree': {
        'title': 'Count Good Nodes In Binary Tree',
        'difficulty': 'Medium', 'topic': 'Trees',
        'statement': "Given the root of a binary tree, a node X is called good if on the path from the root to X there is no node with a value greater than X's value. Return the total number of good nodes in the tree.",
        'func': 'goodNodes',
        'starter': 'def goodNodes(root):\n    pass\n',
        'url': 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/',
        'blind75': False,
    },
    'kth-largest-element-in-a-stream': {
        'title': 'Kth Largest Element In A Stream',
        'difficulty': 'Easy', 'topic': 'Heap',
        'statement': 'Design a class that tracks the kth largest element in a stream of integers. Initialize it with an integer k and an initial array nums, and implement add(val) which inserts val into the stream and returns the kth largest element seen so far.',
        'func': 'KthLargest',
        'starter': 'class KthLargest:\n    def __init__(self, k, nums):\n        pass\n\n    def add(self, val):\n        pass\n',
        'url': 'https://leetcode.com/problems/kth-largest-element-in-a-stream/',
        'blind75': False,
    },
    'last-stone-weight': {
        'title': 'Last Stone Weight',
        'difficulty': 'Easy', 'topic': 'Heap',
        'statement': 'Given an array stones of stone weights, repeatedly smash the two heaviest stones together: if equal both are destroyed, otherwise the lighter is destroyed and the heavier becomes the difference. Return the weight of the last remaining stone, or 0 if no stones remain.',
        'func': 'lastStoneWeight',
        'starter': 'def lastStoneWeight(stones):\n    pass\n',
        'url': 'https://leetcode.com/problems/last-stone-weight/',
        'blind75': False,
    },
    'k-closest-points-to-origin': {
        'title': 'K Closest Points To Origin',
        'difficulty': 'Medium', 'topic': 'Heap',
        'statement': 'Given an array of points on the plane where points[i] = [xi, yi] and an integer k, return the k points closest to the origin (0, 0) using Euclidean distance. The answer may be returned in any order.',
        'func': 'kClosest',
        'starter': 'def kClosest(points, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/k-closest-points-to-origin/',
        'blind75': False,
    },
    'kth-largest-element-in-an-array': {
        'title': 'Kth Largest Element In An Array',
        'difficulty': 'Medium', 'topic': 'Heap',
        'statement': 'Given an integer array nums and an integer k, return the kth largest element in the array. Note this is the kth largest in sorted order, not the kth distinct element.',
        'func': 'findKthLargest',
        'starter': 'def findKthLargest(nums, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
        'blind75': False,
    },
    'task-scheduler': {
        'title': 'Task Scheduler',
        'difficulty': 'Medium', 'topic': 'Heap',
        'statement': 'Given an array tasks of CPU tasks identified by uppercase letters and an integer n representing the minimum cooldown intervals required between two identical tasks, return the minimum number of intervals (each interval being either a task or idle) needed to finish all tasks.',
        'func': 'leastInterval',
        'starter': 'def leastInterval(tasks, n):\n    pass\n',
        'url': 'https://leetcode.com/problems/task-scheduler/',
        'blind75': False,
    },
    'design-twitter': {
        'title': 'Design Twitter',
        'difficulty': 'Medium', 'topic': 'Heap',
        'statement': 'Design a simplified Twitter. Implement postTweet(userId, tweetId), getNewsFeed(userId) which returns the 10 most recent tweet ids from the user and the people they follow, follow(followerId, followeeId), and unfollow(followerId, followeeId).',
        'func': 'Twitter',
        'starter': 'class Twitter:\n    def __init__(self):\n        pass\n\n    def postTweet(self, userId, tweetId):\n        pass\n\n    def getNewsFeed(self, userId):\n        pass\n\n    def follow(self, followerId, followeeId):\n        pass\n\n    def unfollow(self, followerId, followeeId):\n        pass\n',
        'url': 'https://leetcode.com/problems/design-twitter/',
        'blind75': False,
    },
    'subsets': {
        'title': 'Subsets',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given an integer array nums of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets and may be returned in any order.',
        'func': 'subsets',
        'starter': 'def subsets(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/subsets/',
        'blind75': False,
    },
    'combination-sum-ii': {
        'title': 'Combination Sum II',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given an array candidates (which may contain duplicates) and a target, return all unique combinations of candidates that sum to target. Each number may be used at most once in a combination, and the result must not contain duplicate combinations.',
        'func': 'combinationSum2',
        'starter': 'def combinationSum2(candidates, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/combination-sum-ii/',
        'blind75': False,
    },
    'permutations': {
        'title': 'Permutations',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given an array nums of distinct integers, return all possible permutations of its elements. The answer may be returned in any order.',
        'func': 'permute',
        'starter': 'def permute(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/permutations/',
        'blind75': False,
    },
    'subsets-ii': {
        'title': 'Subsets II',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given an integer array nums that may contain duplicates, return all possible subsets (the power set). The solution set must not contain duplicate subsets and may be returned in any order.',
        'func': 'subsetsWithDup',
        'starter': 'def subsetsWithDup(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/subsets-ii/',
        'blind75': False,
    },
    'palindrome-partitioning': {
        'title': 'Palindrome Partitioning',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given a string s, partition it such that every substring of the partition is a palindrome. Return all possible palindrome partitionings of s, where each partitioning is a list of its substrings.',
        'func': 'partition',
        'starter': 'def partition(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/palindrome-partitioning/',
        'blind75': False,
    },
    'letter-combinations-of-a-phone-number': {
        'title': 'Letter Combinations Of A Phone Number',
        'difficulty': 'Medium', 'topic': 'Backtracking',
        'statement': 'Given a string digits containing digits from 2-9, return all possible letter combinations that the number could spell using the standard telephone keypad mapping. Return an empty list if digits is empty; the answer may be in any order.',
        'func': 'letterCombinations',
        'starter': 'def letterCombinations(digits):\n    pass\n',
        'url': 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
        'blind75': False,
    },
    'n-queens': {
        'title': 'N Queens',
        'difficulty': 'Hard', 'topic': 'Backtracking',
        'statement': "Given an integer n, place n queens on an n x n chessboard so that no two queens attack each other (no two share a row, column, or diagonal). Return all distinct solutions, where each solution is a board represented as a list of strings using 'Q' for a queen and '.' for an empty space.",
        'func': 'solveNQueens',
        'starter': 'def solveNQueens(n):\n    pass\n',
        'url': 'https://leetcode.com/problems/n-queens/',
        'blind75': False,
    },
    'rotting-oranges': {
        'title': 'Rotting Oranges',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given an m x n grid where each cell is 0 (empty), 1 (fresh orange), or 2 (rotten orange), every minute any fresh orange adjacent (4-directionally) to a rotten one becomes rotten. Return the minimum number of minutes until no fresh orange remains, or -1 if impossible.',
        'func': 'orangesRotting',
        'starter': 'def orangesRotting(grid):\n    pass\n',
        'url': 'https://leetcode.com/problems/rotting-oranges/',
        'blind75': False,
    },
    'walls-and-gates': {
        'title': 'Walls And Gates',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given an m x n grid where -1 is a wall, 0 is a gate, and 2147483647 (INF) is an empty room, fill each empty room with the distance to its nearest gate. If a room cannot reach any gate, leave it as INF. Modify the grid in place.',
        'func': 'wallsAndGates',
        'starter': 'def wallsAndGates(rooms):\n    pass\n',
        'url': 'https://leetcode.com/problems/walls-and-gates/',
        'blind75': False,
    },
    'surrounded-regions': {
        'title': 'Surrounded Regions',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': "Given an m x n board of 'X' and 'O', capture all regions of 'O' that are completely surrounded by 'X' by flipping them to 'X'. A region is not captured if any of its cells is on the border. Modify the board in place.",
        'func': 'solve',
        'starter': 'def solve(board):\n    pass\n',
        'url': 'https://leetcode.com/problems/surrounded-regions/',
        'blind75': False,
    },
    'course-schedule-ii': {
        'title': 'Course Schedule II',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'Given numCourses labeled 0 to numCourses-1 and a list of prerequisites where [a, b] means b must be taken before a, return an ordering of courses you can take to finish all of them. If multiple valid orderings exist return any; if it is impossible return an empty list.',
        'func': 'findOrder',
        'starter': 'def findOrder(numCourses, prerequisites):\n    pass\n',
        'url': 'https://leetcode.com/problems/course-schedule-ii/',
        'blind75': False,
    },
    'redundant-connection': {
        'title': 'Redundant Connection',
        'difficulty': 'Medium', 'topic': 'Graphs',
        'statement': 'A tree of n nodes labeled 1 to n had one extra edge added, forming exactly one cycle. Given the resulting list of edges, return the edge that can be removed so the graph is again a tree. If multiple answers exist, return the one that appears last in the input.',
        'func': 'findRedundantConnection',
        'starter': 'def findRedundantConnection(edges):\n    pass\n',
        'url': 'https://leetcode.com/problems/redundant-connection/',
        'blind75': False,
    },
    'word-ladder': {
        'title': 'Word Ladder',
        'difficulty': 'Hard', 'topic': 'Advanced Graphs',
        'statement': 'Given two words beginWord and endWord and a wordList, return the number of words in the shortest transformation sequence from beginWord to endWord where each step changes exactly one letter and every intermediate word is in wordList. Return 0 if no such sequence exists.',
        'func': 'ladderLength',
        'starter': 'def ladderLength(beginWord, endWord, wordList):\n    pass\n',
        'url': 'https://leetcode.com/problems/word-ladder/',
        'blind75': False,
    },
    'reconstruct-itinerary': {
        'title': 'Reconstruct Itinerary',
        'difficulty': 'Hard', 'topic': 'Advanced Graphs',
        'statement': "Given a list of airline tickets [from, to], reconstruct the itinerary that uses all tickets exactly once starting from 'JFK'. If multiple valid itineraries exist, return the one with the smallest lexical order when read as a single string of airports.",
        'func': 'findItinerary',
        'starter': 'def findItinerary(tickets):\n    pass\n',
        'url': 'https://leetcode.com/problems/reconstruct-itinerary/',
        'blind75': False,
    },
    'min-cost-to-connect-all-points': {
        'title': 'Min Cost To Connect All Points',
        'difficulty': 'Medium', 'topic': 'Advanced Graphs',
        'statement': 'Given an array of points on a 2D plane, the cost to connect two points is their Manhattan distance. Return the minimum total cost to connect all points so that there is exactly one simple path between any two of them (a minimum spanning tree).',
        'func': 'minCostConnectPoints',
        'starter': 'def minCostConnectPoints(points):\n    pass\n',
        'url': 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
        'blind75': False,
    },
    'network-delay-time': {
        'title': 'Network Delay Time',
        'difficulty': 'Medium', 'topic': 'Advanced Graphs',
        'statement': 'Given a directed weighted graph of n nodes (labeled 1 to n) as times[i] = [u, v, w] meaning a signal takes w time from u to v, and a starting node k, return the minimum time for all nodes to receive the signal, or -1 if some node is unreachable.',
        'func': 'networkDelayTime',
        'starter': 'def networkDelayTime(times, n, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/network-delay-time/',
        'blind75': False,
    },
    'swim-in-rising-water': {
        'title': 'Swim In Rising Water',
        'difficulty': 'Hard', 'topic': 'Advanced Graphs',
        'statement': 'Given an n x n grid where grid[i][j] is the elevation at that cell, at time t the water level is t and you can move 4-directionally between cells whose elevation is at most t. Return the least time t at which you can travel from the top-left cell to the bottom-right cell.',
        'func': 'swimInWater',
        'starter': 'def swimInWater(grid):\n    pass\n',
        'url': 'https://leetcode.com/problems/swim-in-rising-water/',
        'blind75': False,
    },
    'cheapest-flights-within-k-stops': {
        'title': 'Cheapest Flights Within K Stops',
        'difficulty': 'Medium', 'topic': 'Advanced Graphs',
        'statement': 'Given n cities and flights [from, to, price], find the cheapest price to travel from src to dst using at most k stops. Return the cost, or -1 if no such route exists.',
        'func': 'findCheapestPrice',
        'starter': 'def findCheapestPrice(n, flights, src, dst, k):\n    pass\n',
        'url': 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
        'blind75': False,
    },
    'partition-equal-subset-sum': {
        'title': 'Partition Equal Subset Sum',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an integer array nums, return true if the array can be partitioned into two subsets whose sums are equal, otherwise return false.',
        'func': 'canPartition',
        'starter': 'def canPartition(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/partition-equal-subset-sum/',
        'blind75': False,
    },
    'best-time-to-buy-and-sell-stock-with-cooldown': {
        'title': 'Best Time To Buy And Sell Stock With Cooldown',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an array prices where prices[i] is the stock price on day i, find the maximum profit from making any number of transactions, with the rule that after selling you must wait one day (cooldown) before buying again. You may not hold more than one share at a time.',
        'func': 'maxProfit',
        'starter': 'def maxProfit(prices):\n    pass\n',
        'url': 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',
        'blind75': False,
    },
    'coin-change-ii': {
        'title': 'Coin Change II',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': 'Given an integer amount and an array of distinct coin denominations coins (infinite supply of each), return the number of distinct combinations of coins that sum to amount. Return 0 if no combination works.',
        'func': 'change',
        'starter': 'def change(amount, coins):\n    pass\n',
        'url': 'https://leetcode.com/problems/coin-change-ii/',
        'blind75': False,
    },
    'target-sum': {
        'title': 'Target Sum',
        'difficulty': 'Medium', 'topic': '1-D DP',
        'statement': "Given an integer array nums and an integer target, assign a '+' or '-' sign to each number and concatenate them into an expression. Return the number of different sign assignments that make the expression evaluate to target.",
        'func': 'findTargetSumWays',
        'starter': 'def findTargetSumWays(nums, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/target-sum/',
        'blind75': False,
    },
    'interleaving-string': {
        'title': 'Interleaving String',
        'difficulty': 'Medium', 'topic': '2-D DP',
        'statement': 'Given strings s1, s2, and s3, return true if s3 is formed by an interleaving of s1 and s2, preserving the relative order of characters within each string. s3 must use all characters of both s1 and s2.',
        'func': 'isInterleave',
        'starter': 'def isInterleave(s1, s2, s3):\n    pass\n',
        'url': 'https://leetcode.com/problems/interleaving-string/',
        'blind75': False,
    },
    'longest-increasing-path-in-a-matrix': {
        'title': 'Longest Increasing Path In A Matrix',
        'difficulty': 'Hard', 'topic': '2-D DP',
        'statement': 'Given an m x n integer matrix, return the length of the longest strictly increasing path. From each cell you may move 4-directionally to an adjacent cell with a strictly greater value; diagonal moves and wrapping are not allowed.',
        'func': 'longestIncreasingPath',
        'starter': 'def longestIncreasingPath(matrix):\n    pass\n',
        'url': 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/',
        'blind75': False,
    },
    'distinct-subsequences': {
        'title': 'Distinct Subsequences',
        'difficulty': 'Hard', 'topic': '2-D DP',
        'statement': 'Given two strings s and t, return the number of distinct subsequences of s that equal t. A subsequence is formed by deleting zero or more characters without changing the order of the remaining characters.',
        'func': 'numDistinct',
        'starter': 'def numDistinct(s, t):\n    pass\n',
        'url': 'https://leetcode.com/problems/distinct-subsequences/',
        'blind75': False,
    },
    'edit-distance': {
        'title': 'Edit Distance',
        'difficulty': 'Medium', 'topic': '2-D DP',
        'statement': 'Given two strings word1 and word2, return the minimum number of operations to convert word1 into word2. The allowed operations are inserting a character, deleting a character, and replacing a character.',
        'func': 'minDistance',
        'starter': 'def minDistance(word1, word2):\n    pass\n',
        'url': 'https://leetcode.com/problems/edit-distance/',
        'blind75': False,
    },
    'burst-balloons': {
        'title': 'Burst Balloons',
        'difficulty': 'Hard', 'topic': '2-D DP',
        'statement': 'Given an array nums of balloon values, bursting balloon i earns nums[i-1] * nums[i] * nums[i+1] coins, where out-of-range neighbors are treated as 1. Return the maximum coins you can collect by bursting all balloons in an optimal order.',
        'func': 'maxCoins',
        'starter': 'def maxCoins(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/burst-balloons/',
        'blind75': False,
    },
    'regular-expression-matching': {
        'title': 'Regular Expression Matching',
        'difficulty': 'Hard', 'topic': '2-D DP',
        'statement': "Given an input string s and a pattern p, implement regular expression matching where '.' matches any single character and '*' matches zero or more of the preceding element. The match must cover the entire string s. Return true if they match.",
        'func': 'isMatch',
        'starter': 'def isMatch(s, p):\n    pass\n',
        'url': 'https://leetcode.com/problems/regular-expression-matching/',
        'blind75': False,
    },
    'jump-game-ii': {
        'title': 'Jump Game II',
        'difficulty': 'Medium', 'topic': 'Greedy',
        'statement': 'Given an array nums where nums[i] is the maximum forward jump length from index i, return the minimum number of jumps to reach the last index. It is guaranteed that you can always reach the last index.',
        'func': 'jump',
        'starter': 'def jump(nums):\n    pass\n',
        'url': 'https://leetcode.com/problems/jump-game-ii/',
        'blind75': False,
    },
    'gas-station': {
        'title': 'Gas Station',
        'difficulty': 'Medium', 'topic': 'Greedy',
        'statement': 'There are n gas stations in a circle; gas[i] is the fuel available at station i and cost[i] is the fuel needed to travel from station i to i+1. Return the starting station index from which you can complete the circuit once, or -1 if it is impossible. The answer is guaranteed to be unique if it exists.',
        'func': 'canCompleteCircuit',
        'starter': 'def canCompleteCircuit(gas, cost):\n    pass\n',
        'url': 'https://leetcode.com/problems/gas-station/',
        'blind75': False,
    },
    'hand-of-straights': {
        'title': 'Hand Of Straights',
        'difficulty': 'Medium', 'topic': 'Greedy',
        'statement': 'Given an integer array hand of card values and an integer groupSize, return true if the cards can be rearranged into groups of exactly groupSize consecutive cards, otherwise return false.',
        'func': 'isNStraightHand',
        'starter': 'def isNStraightHand(hand, groupSize):\n    pass\n',
        'url': 'https://leetcode.com/problems/hand-of-straights/',
        'blind75': False,
    },
    'merge-triplets-to-form-target-triplet': {
        'title': 'Merge Triplets To Form Target Triplet',
        'difficulty': 'Medium', 'topic': 'Greedy',
        'statement': 'Given a list of triplets and a target triplet, you may repeatedly pick two triplets and replace them with their element-wise maximum. Return true if it is possible to obtain the target triplet, using only triplets whose every element is less than or equal to the corresponding target element.',
        'func': 'mergeTriplets',
        'starter': 'def mergeTriplets(triplets, target):\n    pass\n',
        'url': 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/',
        'blind75': False,
    },
    'partition-labels': {
        'title': 'Partition Labels',
        'difficulty': 'Medium', 'topic': 'Greedy',
        'statement': 'Given a string s, partition it into as many parts as possible so that each letter appears in at most one part. Return a list of the sizes of these parts, in order; the parts must concatenate back to s.',
        'func': 'partitionLabels',
        'starter': 'def partitionLabels(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/partition-labels/',
        'blind75': False,
    },
    'valid-parenthesis-string': {
        'title': 'Valid Parenthesis String',
        'difficulty': 'Medium', 'topic': 'Greedy',
        'statement': "Given a string s containing '(', ')', and '*', where '*' can be treated as '(', ')', or an empty string, return true if s can be made into a valid parentheses expression.",
        'func': 'checkValidString',
        'starter': 'def checkValidString(s):\n    pass\n',
        'url': 'https://leetcode.com/problems/valid-parenthesis-string/',
        'blind75': False,
    },
    'minimum-interval-to-include-each-query': {
        'title': 'Minimum Interval To Include Each Query',
        'difficulty': 'Hard', 'topic': 'Intervals',
        'statement': 'Given a list of intervals [left, right] and an array of queries, for each query q find the size (right - left + 1) of the smallest interval that contains q. Return an array of answers, using -1 when no interval contains the query.',
        'func': 'minInterval',
        'starter': 'def minInterval(intervals, queries):\n    pass\n',
        'url': 'https://leetcode.com/problems/minimum-interval-to-include-each-query/',
        'blind75': False,
    },
    'happy-number': {
        'title': 'Happy Number',
        'difficulty': 'Easy', 'topic': 'Math & Bit',
        'statement': 'A number is happy if repeatedly replacing it with the sum of the squares of its digits eventually reaches 1; otherwise the process loops endlessly. Given an integer n, return true if it is a happy number.',
        'func': 'isHappy',
        'starter': 'def isHappy(n):\n    pass\n',
        'url': 'https://leetcode.com/problems/happy-number/',
        'blind75': False,
    },
    'plus-one': {
        'title': 'Plus One',
        'difficulty': 'Easy', 'topic': 'Math & Bit',
        'statement': 'Given a non-empty array of digits representing a non-negative integer (most significant digit first), increment the integer by one and return the resulting array of digits.',
        'func': 'plusOne',
        'starter': 'def plusOne(digits):\n    pass\n',
        'url': 'https://leetcode.com/problems/plus-one/',
        'blind75': False,
    },
    'powx-n': {
        'title': 'Pow(x, n)',
        'difficulty': 'Medium', 'topic': 'Math & Bit',
        'statement': 'Implement pow(x, n), which computes x raised to the power n (n can be negative). Return the result as a float.',
        'func': 'myPow',
        'starter': 'def myPow(x, n):\n    pass\n',
        'url': 'https://leetcode.com/problems/powx-n/',
        'blind75': False,
    },
    'multiply-strings': {
        'title': 'Multiply Strings',
        'difficulty': 'Medium', 'topic': 'Math & Bit',
        'statement': 'Given two non-negative integers num1 and num2 represented as strings, return their product as a string. You must not use built-in big integer libraries or convert the inputs to integers directly.',
        'func': 'multiply',
        'starter': 'def multiply(num1, num2):\n    pass\n',
        'url': 'https://leetcode.com/problems/multiply-strings/',
        'blind75': False,
    },
    'detect-squares': {
        'title': 'Detect Squares',
        'difficulty': 'Medium', 'topic': 'Math & Bit',
        'statement': 'Design a data structure that adds points in a 2D plane and counts axis-aligned squares. Implement add(point) to add a point (duplicates allowed) and count(point) to return the number of ways to form an axis-aligned square with positive area using the query point as one corner and three previously added points as the others.',
        'func': 'DetectSquares',
        'starter': 'class DetectSquares:\n    def __init__(self):\n        pass\n\n    def add(self, point):\n        pass\n\n    def count(self, point):\n        pass\n',
        'url': 'https://leetcode.com/problems/detect-squares/',
        'blind75': False,
    },
}

ORDER = list(CATALOG.keys())

