"""Generate the GitKosh app icon, README logo, and embedded header logo.

Produces:
  - dist_icon/icon_1024.png      (master, for .icns via iconutil)
  - dist_icon/logo_72.png        (small raster)
  - docs/logo.png                (README header logo)
  - app/logo_data.py             (base64 of a 72px logo for the Tk header)

Mark: an indigo gradient rounded square holding a white binary tree of
connected nodes — trees & graphs are the emblem of data structures &
algorithms, the craft GitKosh helps you learn, practice and collect.
"""
import base64
import os

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(__file__))
OUT_DIR = os.path.join(ROOT, "dist_icon")
APP_DIR = os.path.join(ROOT, "app")
DOCS_DIR = os.path.join(ROOT, "docs")
S = 1024
TOP = (129, 140, 248)   # indigo-400
BOT = (79, 70, 229)     # indigo-600
WHITE = (255, 255, 255, 255)


def build():
    os.makedirs(OUT_DIR, exist_ok=True)
    # macOS icons leave a transparent margin (~10%); art occupies the inset square.
    margin = 100
    x0, y0 = margin, margin
    side = S - 2 * margin
    x1, y1 = x0 + side, y0 + side

    # vertical gradient masked to the inset rounded square
    grad = Image.new("RGBA", (S, S))
    gd = ImageDraw.Draw(grad)
    for y in range(S):
        t = y / S
        gd.line([(0, y), (S, y)], fill=(
            int(TOP[0] * (1 - t) + BOT[0] * t),
            int(TOP[1] * (1 - t) + BOT[1] * t),
            int(TOP[2] * (1 - t) + BOT[2] * t), 255))
    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle([x0, y0, x1, y1], radius=int(side * 0.225), fill=255)
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    img.paste(grad, (0, 0), mask)

    d = ImageDraw.Draw(img)
    cx = S // 2
    # binary tree: a root branching down to two children
    root = (cx, 372)
    left = (cx - 150, 652)
    right = (cx + 150, 652)
    nodes = [root, left, right]
    R = 78          # node radius
    ew = 48         # edge width

    # edges first (centre-to-centre), nodes drawn over the ends
    for child in (left, right):
        d.line([root, child], fill=WHITE, width=ew)
        # round the joints
    for (nx, ny) in nodes:
        d.ellipse([nx - R, ny - R, nx + R, ny + R], fill=WHITE)
    # hollow out the children a touch to read as distinct nodes (subtle facets)
    inner = int(R * 0.42)
    grad_at = lambda y: (
        int(TOP[0] * (1 - y / S) + BOT[0] * (y / S)),
        int(TOP[1] * (1 - y / S) + BOT[1] * (y / S)),
        int(TOP[2] * (1 - y / S) + BOT[2] * (y / S)), 255)
    for (nx, ny) in (left, right):
        d.ellipse([nx - inner, ny - inner, nx + inner, ny + inner], fill=grad_at(ny))

    master = os.path.join(OUT_DIR, "icon_1024.png")
    img.save(master)
    print("wrote", master)

    # README logo (square, sized down by the README's width attr)
    os.makedirs(DOCS_DIR, exist_ok=True)
    logo = img.resize((512, 512), Image.LANCZOS)
    logo.save(os.path.join(DOCS_DIR, "logo.png"))
    print("wrote", os.path.join(DOCS_DIR, "logo.png"))

    # header logo (72px) -> base64 into app/logo_data.py
    small = img.resize((72, 72), Image.LANCZOS)
    sp = os.path.join(OUT_DIR, "logo_72.png")
    small.save(sp)
    b64 = base64.b64encode(open(sp, "rb").read()).decode("ascii")
    with open(os.path.join(APP_DIR, "logo_data.py"), "w") as f:
        f.write('"""Embedded header logo (base64 PNG) — generated by tools/make_icon.py."""\n')
        f.write(f'LOGO_PNG_B64 = "{b64}"\n')
    print("wrote app/logo_data.py")


if __name__ == "__main__":
    build()
